version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rdS
    ports:
      - 3307:3306

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: P@ssw0rdS
    ports:
      - 15672:15672
      - 5672:5672