spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  data:
    rest:
      base-path: /api
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: localhost
    username: user
    password: P@ssw0rdS
zett:
  rabbitmq:
    queue: notificationQueue
server:
  port: 5000
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3307/schema_user
    username: root
    password: ENC(AnepqY3A6WvH0NRi9aNuXa+LQ480CLRA)

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://remotemysql.com:3306/nvJnXNaMZQ
    username: nvJnXNaMZQ
    password: ENC(fX4aHGzKaXz9B/g2Pj5U8bdkgJYn47OZ)
  rabbitmq:
    host: buck.rmq.cloudamqp.com
    username: fobqquzn
    password: ENC(0EneS1T3kJOBdXj5buFTis1zKuWq0t8xvCnBvZ7Rjfz/Jv/CtJ8NP4qYEmT/WPM3)
    port: 1883