spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  data:
    rest:
      base-path: /api
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 5000
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3307/schema_user
    username: root
    password: ENC(AnepqY3A6WvH0NRi9aNuXa+LQ480CLRA)

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://remotemysql.com:3306/nvJnXNaMZQ
    username: nvJnXNaMZQ
    password: ENC(fX4aHGzKaXz9B/g2Pj5U8bdkgJYn47OZ)
